<?php

/**
 * @file
 * Code related to paragraphs formatters.
 */

// This is bad, but loads the inc files.
require_once dirname(__FILE__) . '/paragraphs_formatters.field_formatter.inc';
require_once dirname(__FILE__) . '/paragraphs_formatters.field_widget.inc';

/**
 * Implements hook_entity_info_alter().
 */
function paragraphs_formatters_entity_info_alter(&$entity_info) {
  if (isset($entity_info['paragraphs_item'])) {
    $entity_info['paragraphs_item']['label callback'] = 'paragraphs_formatters_label';
  }
}

/**
 * Label callback.
 */
function paragraphs_formatters_label($entity) {
  // [bundle name] #[eid] on [parent bundle] [parent title] 
  $output = $entity->bundle() . ' #' . $entity->item_id . ' on ';

  $host = $entity->hostEntity();
  $output .= $host->type . ' ' . $host->title;

  return $output;
}